# -*- coding: utf-8 -*-
"""Testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWP-z75Q3XaFbPs0Wwhrp5tmNWC4RmVo
"""

import streamlit as st
from streamlit_calendar import calendar_component
import pandas as pd

# Title of the app
st.title("Streamlit Calendar App")

# Sidebar for creating new events
st.sidebar.header("Add New Event")
event_name = st.sidebar.text_input("Event Name")
event_date = st.sidebar.date_input("Event Date")
event_time = st.sidebar.time_input("Event Time")
add_event = st.sidebar.button("Add Event")

# Placeholder for storing events
if "events" not in st.session_state:
    st.session_state["events"] = []

# Add new event
if add_event:
    new_event = {
        "title": event_name,
        "start": pd.Timestamp(event_date).replace(hour=event_time.hour, minute=event_time.minute),
        "end": pd.Timestamp(event_date).replace(hour=event_time.hour + 1, minute=event_time.minute),
    }
    st.session_state["events"].append(new_event)
    st.sidebar.success("Event added successfully!")

# Display the calendar
st.header("Your Calendar")
events = st.session_state["events"]
selected_date = calendar_component(events=events)

# Show selected date details
if selected_date:
    st.subheader("Selected Date Details")
    selected_date_events = [event for event in events if pd.Timestamp(event["start"]).date() == pd.Timestamp(selected_date).date()]
    if selected_date_events:
        for event in selected_date_events:
            st.write(f"**{event['title']}** - {event['start'].strftime('%Y-%m-%d %H:%M')} to {event['end'].strftime('%H:%M')}")
    else:
        st.write("No events on this day.")