# -*- coding: utf-8 -*-
"""Test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7LWhObJYHNsSaFBI8eRL9iaclv1Rxxz
"""

import openai
import streamlit as st

# Set your OpenAI API Key
openai.api_key = "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"  # Replace with your OpenAI API key

# Streamlit app
def main():
    st.title("OpenAI API Test App")
    st.markdown("This is a basic app to test the OpenAI API integration.")

    # Input prompt
    user_input = st.text_area("Enter your prompt:", placeholder="Type something here...")

    # Submit button
    if st.button("Get Response"):
        if user_input.strip():
            try:
                # Call OpenAI API
                response = openai.Completion.create(
                    engine="text-davinci-003",
                    prompt=user_input,
                    max_tokens=100
                )
                # Display response
                st.subheader("OpenAI Response:")
                st.write(response["choices"][0]["text"].strip())
            except Exception as e:
                st.error(f"An error occurred: {e}")
        else:
            st.warning("Please enter a prompt.")

if __name__ == "__main__":
    main()